### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by smadds** [jthomas/node-red-contrib-npm#4]
Not a code issue - just would appreciate some help in how to use this.

I am looking to use the udmx node in node-red (https://www.npmjs.com/package/udmx). I installed it using npm, but am unclear how to configure your module to talk to it.

These are the instructions:-

**Sample usage:**

```
#!/usr/bin/env nodejs
 
var uDMX = require('udmx');
 
var dmx = new uDMX();
 
dmx.on('channel-all', (channel, value) => {console.log(channel + ' => ' + value);});
dmx.on('connected', () => {console.log('Connected');});
 
dmx.connect();
 
setInterval(() => {dmx.set(Math.round(Math.random() * 512), Math.round(Math.random() * 255));}, 1000);
```

**Comment by jthomas** [comment]
Unfortunately this node cannot be used with the uDMX package due to the way Node-RED operates. Using this package with Node-RED will require creating a custom node. There's a "Getting Started" guide available here: https://nodered.org/docs/creating-nodes/

If you do create a custom node, consider publishing it on Github for others to use!

I'm going to close this issue as it's not resolvable using this node I'm afraid.
